// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CountButton: typeof import('./src/components/CountButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Hi: typeof import('./src/components/Hi.vue')['default']
  }
}

export { }
